// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/juker1141/simplebank/worker (interfaces: TaskDistribtor)

// Package mockwk is a generated GoMock package.
package mockwk

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	asynq "github.com/hibiken/asynq"
	worker "github.com/juker1141/simplebank/worker"
)

// MockTaskDistribtor is a mock of TaskDistribtor interface.
type MockTaskDistribtor struct {
	ctrl     *gomock.Controller
	recorder *MockTaskDistribtorMockRecorder
}

// MockTaskDistribtorMockRecorder is the mock recorder for MockTaskDistribtor.
type MockTaskDistribtorMockRecorder struct {
	mock *MockTaskDistribtor
}

// NewMockTaskDistribtor creates a new mock instance.
func NewMockTaskDistribtor(ctrl *gomock.Controller) *MockTaskDistribtor {
	mock := &MockTaskDistribtor{ctrl: ctrl}
	mock.recorder = &MockTaskDistribtorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskDistribtor) EXPECT() *MockTaskDistribtorMockRecorder {
	return m.recorder
}

// DistributeTaskSendVerifyEmail mocks base method.
func (m *MockTaskDistribtor) DistributeTaskSendVerifyEmail(arg0 context.Context, arg1 *worker.PayloadSendVerifyEmail, arg2 ...asynq.Option) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DistributeTaskSendVerifyEmail", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DistributeTaskSendVerifyEmail indicates an expected call of DistributeTaskSendVerifyEmail.
func (mr *MockTaskDistribtorMockRecorder) DistributeTaskSendVerifyEmail(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DistributeTaskSendVerifyEmail", reflect.TypeOf((*MockTaskDistribtor)(nil).DistributeTaskSendVerifyEmail), varargs...)
}
